### ISSUE TITLE
ValueError when reading a Mark5B data

### ISSUE THREAD

**Issue by shaoguangleo** [mhvk/baseband#107]
Hi @cczhu  @mhvk :
When I using the following code to reading a Mark5B data, I encounter some problem.

**CODE** is 

`
from baseband.baseband import mark5b
from astropy.time import Time

def get_data_time(file_name, ref_day):
    with open(file_name, 'rb') as fh:
        header = mark5b.Mark5BHeader.fromfile(fh, ref_mjd=Time(ref_day).mjd)
        return header

if __name__ == '__main__':
    get_data_time('test.m5b', '2010-01-01')
`

The **OUTPUT** is 

`
Traceback (most recent call last):
  File "/private/tmp/test/src/baseband/baseband/vlbi_base/utils.py", line 9, in bcd_decode
    return int('{:x}'.format(value))
ValueError: invalid literal for int() with base 10: 'cc0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "readmark5b.py", line 10, in <module>
    get_data_time('test.m5b', '2010-01-01')
  File "readmark5b.py", line 6, in get_data_time
    header = mark5b.Mark5BHeader.fromfile(fh, ref_mjd=Time(ref_day).mjd)
  File "/private/tmp/test/src/baseband/baseband/vlbi_base/header.py", line 353, in fromfile
    return cls(cls._struct.unpack(s), *args, **kwargs)
  File "/private/tmp/test/src/baseband/baseband/mark5b/header.py", line 89, in __init__
    self._header_parser.parsers['bcd_jday'](words))
  File "/private/tmp/test/src/baseband/baseband/vlbi_base/utils.py", line 13, in bcd_decode
    .format(value, hex(value)))
ValueError: Invalid BCD encoded value 3264=0xcc0.
`

Do you have any ideas?

**Comment by cczhu** [comment]
Hi @shaoguangleo,

That looks like you have a corrupt header.  Individual hex digits in the jday BCD should not exceed 9, and yours has `c`s.  You can test if your code works (it works on my machine) by replacing `test.m5b` with `SAMPLE_MARK5B`, which you can import from the `baseband` module via

```
from baseband.baseband.data import SAMPLE_MARK5B
```

For a fix within Baseband, you can have a look at my post in #89 to make a hack [to override the value](https://github.com/mhvk/baseband/issues/89#issuecomment-342888103).  If multiple headers or sections of the file are corrupted, writing a workaround in Baseband becomes more involved.
