### ISSUE TITLE
Reading problems with ARO file

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband#370]
(from e-mail from Hsiu-Hsien)
Hi Marten,

1) I copied a problematic file to the cita cluster at
/mnt/raid-project/gmrt/hhlin/share_mhvk/aro10m/0006221050.vdif

the output of fh.info:
```
{'start_time': <Time object: scale='utc' format='isot'
value=2020-01-18T19:29:20.505246720>, 'stop_time': <Time object:
scale='utc' format='isot' value=2020-01-18T19:29:20.589132800>,
'sample_rate': <Quantity 0.390625 MHz>, 'shape': (32768, 2, 1024),
'format': 'vdif', 'bps': 4, 'complex_data': True, 'verify': 'fix',
'readable': True, 'checks': OrderedDict([('decodable', True),
('continuous', 'no obvious gaps')]), 'errors': OrderedDict([('frame_rate',
EOFError()), ('start_time', ValueError('this header does not provide a
frame rate. Pass it in explicitly.'))]), 'file_info': {'format': 'vdif',
'edv': 0, 'number_of_frames': 65536, 'thread_ids': [0, 1],
'number_of_framesets': 32768, 'samples_per_frame': 1, 'sample_shape': (2,
1024), 'bps': 4, 'complex_data': True, 'readable': True, 'checks':
OrderedDict([('decodable', True)]), 'errors': OrderedDict([('frame_rate',
EOFError()), ('start_time', ValueError('this header does not provide a
frame rate. Pass it in explicitly.'))])}}
```

2) It was fine to read a short duration (0.001 seconds), while there would
be `EOFError` or `ValueError` when the duration is longer. With playing with
different reading duration (I tried 0.01, 0.1, 0.15, 0.5 seconds), the
error shows up as below. Do you think it's an error related to the vdif
writing process?

```
/home/arofrb/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1076-py3.7.egg/baseband/vdif/base.py:729:
UserWarning: problem loading frame set 11778. The frame set seems to be
missing altogether. All threads set to invalid.
  warnings.warn(msg)
/home/arofrb/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1076-py3.7.egg/baseband/vdif/base.py:729:
UserWarning: problem loading frame set 11779. The frame set seems to be
missing altogether. All threads set to invalid.
  warnings.warn(msg)
```

Best,
Hsiu-Hsien

**Comment by mhvk** [comment]
Preliminary: info in clearer format (with small update)
```
fh.info  # Don't put parentheses for nice output!
Stream information:
start_time = 2020-01-18T19:29:20.505246720
stop_time = 2020-01-18T19:29:20.589132800
sample_rate = 0.390625 MHz
shape = (32768, 2, 1024)
format = vdif
bps = 4
complex_data = True
verify = fix
readable = True

checks:  decodable: True
         continuous: no obvious gaps

errors:  frame_rate: EOFError()

File information:
edv = 0
number_of_frames = 65536
thread_ids = [0, 1]
number_of_framesets = 32768
samples_per_frame = 1
sample_shape = (2, 1024)
```

**Comment by mhvk** [comment]
Looking through the file, near frame set `11778` for which there is a warning:
```
In [64]: fh.fh_raw.seek(11776*fh.header0.frame_nbytes*2)
Out[64]: 24870912

In [65]: for i in range(10):
    ...:     h = fh.fh_raw.read_frame().header
    ...:     print(i, h['seconds'], h['frame_nr'])
    ...:     
0 64610960 209138
1 64610960 209138
2 64610960 209139
3 64610960 209139
4 64610968 360940
5 64610968 360940
6 64610968 360941
7 64610968 360941
8 64610968 360942
9 64610968 360942
```
So a jump by 8 seconds and a different frame number...

But the last header has:
```
fh._last_header['seconds'], fh._last_header['frame_nr']
(64610960, 230129)
```
Investigating further: there are exactly 2946 frames with the wrong seconds/frame number in there, or 1473 framesets (11778-13250 inclusive).

**Comment by mhvk** [comment]
I checked also with the previous version of baseband, and I do get an error for this file. In your tests, did you run with `verify=False` or using `python3 -O` (optimized python removes `assert`, so is more or less equivalent to running with `verify=False`).

**Comment by mhvk** [comment]
Actually, one thing I had not yet noticed, but is the case, is that *all* frames in this file are invalid.  So, I can probably make a work-around that for invalid frames just gives up instead of trying to find the right frame number.

**Comment by hsiuhsil** [comment]
Hi Marten, 

I just double-check that reading this vdif file with older baseband, and I do get an EOFError even if I set verify=False in the read frame. 

Sorry for the wrong information. I must mix up with other things.

Best,
Hsiu-Hsien

**Comment by tcassanelli** [comment]
I am experiencing the same problem, I `checkout` to branches `v3.0.x` and `v2.0.x` and I am still getting the same error (in other data set that I tested before with no problems),

* branch `3.0.dev1078`
```
Traceback (most recent call last):
  File "/home/v/vanderli/cassane/babendil-frb-vlbi/scripts/calibrator_search7.py", line 97, in <module>
    verify=False
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/io/reader.py", line 175, in read_n_frames
    V = fh.read(n_frames)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev394-py3.7.egg/scintillometry/base.py", line 311, in read
    self._frame = self._read_frame(frame_index)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev394-py3.7.egg/scintillometry/base.py", line 559, in _read_frame
    data = self.ih.read(self._raw_samples_per_frame)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1078-py3.7.egg/baseband/vlbi_base/base.py", line 788, in read
    self._frame = self._read_frame(frame_index)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1078-py3.7.egg/baseband/vlbi_base/base.py", line 816, in _read_frame
    return self._fh_raw_read_frame()
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1078-py3.7.egg/baseband/vdif/base.py", line 520, in _fh_raw_read_frame
    verify=self.verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1078-py3.7.egg/baseband/vdif/base.py", line 144, in read_frameset
    verify=verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1078-py3.7.egg/baseband/vdif/frame.py", line 233, in fromfile
    header0 = VDIFHeader.fromfile(fh, edv, verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1078-py3.7.egg/baseband/vdif/header.py", line 174, in fromfile
    raise EOFError
EOFError
```

* branch `3.0.x`
```
Traceback (most recent call last):
  File "/home/v/vanderli/cassane/babendil-frb-vlbi/scripts/calibrator_search7.py", line 97, in <module>
    verify=False
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/io/reader.py", line 175, in read_n_frames
    V = fh.read(n_frames)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev394-py3.7.egg/scintillometry/base.py", line 311, in read
    self._frame = self._read_frame(frame_index)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev394-py3.7.egg/scintillometry/base.py", line 559, in _read_frame
    data = self.ih.read(self._raw_samples_per_frame)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.0-py3.7.egg/baseband/vlbi_base/base.py", line 584, in read
    self._frame = self._read_frame(frame_index)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.0-py3.7.egg/baseband/vdif/base.py", line 467, in _read_frame
    verify=self.verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.0-py3.7.egg/baseband/vdif/base.py", line 124, in read_frameset
    verify=verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.0-py3.7.egg/baseband/vdif/frame.py", line 232, in fromfile
    header0 = VDIFHeader.fromfile(fh, edv, verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-3.0.0-py3.7.egg/baseband/vdif/header.py", line 166, in fromfile
    raise EOFError
EOFError
```

* branch `2.0.x`
```
Traceback (most recent call last):
  File "/home/v/vanderli/cassane/babendil-frb-vlbi/scripts/calibrator_search7.py", line 97, in <module>
    verify=False
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/io/reader.py", line 175, in read_n_frames
    V = fh.read(n_frames)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev394-py3.7.egg/scintillometry/base.py", line 311, in read
    self._frame = self._read_frame(frame_index)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev394-py3.7.egg/scintillometry/base.py", line 559, in _read_frame
    data = self.ih.read(self._raw_samples_per_frame)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-2.0.1.dev854-py3.7.egg/baseband/vlbi_base/base.py", line 578, in read
    self._frame = self._read_frame(frame_index)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-2.0.1.dev854-py3.7.egg/baseband/vdif/base.py", line 468, in _read_frame
    verify=self.verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-2.0.1.dev854-py3.7.egg/baseband/vdif/base.py", line 125, in read_frameset
    verify=verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-2.0.1.dev854-py3.7.egg/baseband/vdif/frame.py", line 236, in fromfile
    header0 = VDIFHeader.fromfile(fh, edv, verify)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/baseband-2.0.1.dev854-py3.7.egg/baseband/vdif/header.py", line 169, in fromfile
    raise EOFError
EOFError
```

**Comment by mhvk** [comment]
@tcassanelli - I am confused: how can you have read this before with no problem if you now do have problems on all versions of baseband? Do you mean with a different setting of `verify`?

**Comment by mhvk** [comment]
p.s. Not sure that this is in fact the same issue. Easiest would be a new one with a specific file to look at...

**Comment by tcassanelli** [comment]
yes, I am confused too, I tried with both `verify` options and it shows the same error. Not sure why it is failing with previous versions. 

The directory for these data are:
* `/scratch/p/pen/hsiuhsil/drao_data/VLBI_ARO/2019Sep/20190905T124705Z_chime_psr_vdif/*/*.vdif`
* `/scratch/v/vanderli/cassane/VLBI_data/Sep2019_46m/20190905T124658Z_aro_vdif/*.vdif`

(Hope by now you have access to my data, the first data set is under @hsiuhsil)
Both of them are giving me the same error. I will inspect this more carefully tomorrow.

**Comment by mhvk** [comment]
Sadly, I cannot access either set of files (though really it would help to be clearer *which* of the files in those directories causes a problem...); it get permission errors if I try to go beyond
```
/scratch/p/pen/hsiuhsil/ # need chmod o+rx for drao_data and probably beyond
/scratch/v/vanderli/ # same for cassane
```

**Comment by mhvk** [comment]
Fix for @hsiuhsil 's problem (I think) in #372 - I don't think this will fix @tcassanelli's, though, since that one doesn't even work with `verify=False`...

@hsiuhsil - I tested my fix on the file you linked to above, but it would be good to do a more extensive trial...

p.s. Separately, it would be nice if ARO did not produce non-compliant data - could someone ask whether it is possible to store the correct frame number and seconds (basically, a correct header) even when data is missing??

**Comment by tcassanelli** [comment]
Just talked to Andre and this is been in his TODO list for a while. He hasn't had time, I'll see next week what we can do about it.

**Comment by hsiuhsil** [comment]
> @hsiuhsil - I tested my fix on the file you linked to above, but it would be good to do a more extensive trial...
> 
@mhvk : I copied a few more aro-10m vdif files to the CITA cluster at:
/mnt/raid-project/gmrt/hhlin/share_mhvk/aro10m

**Comment by tcassanelli** [comment]
Ok so I think I know where is the problem now (after spending most of the day trying to debug this).
The problem wasn't in any of the `basband` versions, it was at the time where I was calling the script. Basically what I was doing is:

```python
In [1]: import babendil
   ...: from astropy import units as u
   ...: from astropy.time import Time
   ...: from baseband import vdif, helpers
   ...: import numpy as np
   ...:
   ...: freq_resolution = 390625 * u.Hz
   ...:
   ...: directoryB = '/scratch/v/vanderli/cassane/VLBI_data/Sep2019_46m/20190905T133158Z_aro
   ...: _vdif/*.vdif'
   ...:
   ...: data_sortedB = babendil.utils.sort_files(directoryB)
   ...:
   ...: timestampB = Time(
   ...:     '2019-09-05T13:33:35.151490760', format='isot', scale='utc', precision=9)
   ...:
   ...: t_integration = 1 * u.s
   ...: n_frames = np.ceil((t_integration * freq_resolution).decompose()).astype(int)
   ...: print('n_frames:', n_frames)
   ...:
   ...: fraw = helpers.sequentialfile.open(data_sortedB, 'rb')
   ...: fh = vdif.open(fraw, mode='rs', sample_rate=freq_resolution, verify=False)
   ...:
   ...: fh.seek(timestampB)
   ...: VB = fh.read(n_frames)
   ...:
   ...: print('VB.shape:', VB.shape)
   ...: print('n_frames:', n_frames)
n_frames: 390625
VB.shape: (390625, 2, 1024)
n_frames: 0
```
where initially `n_frames` is a dimensionless `astropy.quantity.Quantity`, works the first time, but after going through the `fh.read` it goes to zero! Which is very **weird**. It is easy to solve, simple use a python integer. 

The other error that could have returned the `EOFError` is that there were missing files in the directory that I was using. In brief, I use data sets from CHIME (stored at Hsiu-Hsien's) and from ARO (stored in my `$SCRATCH`). I didn't know that files must be used by the original user otherwise they get purged. My dataset was fine but Hsiu-Hsien had some missing data. I will restore the data and see whether this solves the problem.

**Comment by mhvk** [comment]
Ah, I must be doing some in-place calculation with `n_frames` somewhere - I'll see if I can chase that down since this clearly leads to very hard to debug problems!

**Comment by mhvk** [comment]
@tcassanelli - fix for the `count` issue in #373. Thanks very much for uncovering that!!! I'll fix it in scintillometry too.

**Comment by mhvk** [comment]
Here's to hoping that restoring the files will make things work... (in principle, the code should now be able to deal with gaps, but of course you'd get zeros where you have real data, so better have the right input!!).

**Comment by mhvk** [comment]
I've closed since I *think* all the problems discussed here were fix. Do reopen if not true (or, perhaps better, open a new issue)
